spring:
  application:
    name: board

  config:
    import:
      - optional:file:.env[.properties]

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password:
    # ${DB_PASSWORD}
    # password: ${{ secrets.CI_DB_PASSWORD }}

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false

  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET_NAME}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION:ap-northeast-2}
      auto: false
    stack:
      auto: false

management:
  endpoints:
    web:
      exposure:
        include: health, info

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: ${JWT_SECRET}
  access-token-exp-seconds: 300
  refresh-token-exp-seconds: 12096000

